### ISSUE TITLE
如何实现一个http 连接池？

### ISSUE THREAD

**Issue by fuyao-w** [goctx/generic-pool#3]
如何实现一个http 的连接池？我认为最终要的是我想保持的http 链接实际是什么样子的，具体保持了那些内存信息？可以服用的基础是什么？（就像java线程池，我知道java 线程的实现是对系统函数的封装，java 线程本身就是个代理。并且没有在某一点暂停的直接方法，完成一个池只需要让线程不停止运行，即是从阻塞队列中不断获取任务，一个http 链接在系统中实际又是什么状态呢？？？）
能给我提供个思路吗？最好是从哪里，那本书可以找到相关的知识。

**Comment by xialeistudio** [comment]
问题已收到，http连接池这个东西你可以说详细点吗，比如用在什么场景？目前我能想到的是提供一个容器保存很多http链接而已


 
---原始邮件---
发件人: "Wangfuyao"<notifications@github.com&gt;
发送时间: 2019年9月20日(星期五) 晚上9:44
收件人: "goctx/generic-pool"<generic-pool@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [goctx/generic-pool] 如何实现一个http 连接池？ (#3)



如何实现一个http 的连接池？我认为最终要的是我想保持的http 链接实际是什么样子的，具体保持了那些内存信息？可以服用的基础是什么？（就像java线程池，我知道java 线程的实现是对系统函数的封装，java 线程本身就是个代理。并且没有在某一点暂停的直接方法，完成一个池只需要让线程不停止运行，即是从阻塞队列中不断获取任务，一个http 链接在系统中实际又是什么状态呢？？？）
 能给我提供个思路吗？最好是从哪里，那本书可以找到相关的知识。

**Comment by TransientWang** [comment]
> 问题已收到，http连接池这个东西你可以说详细点吗，比如用在什么场景？目前我能想到的是提供一个容器保存很多http链接而已
> […](#)
> ---原始邮件--- 发件人: "Wangfuyao"<notifications@github.com&gt; 发送时间: 2019年9月20日(星期五) 晚上9:44 收件人: "goctx/generic-pool"<generic-pool@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [goctx/generic-pool] 如何实现一个http 连接池？ (#3) 如何实现一个http 的连接池？我认为最终要的是我想保持的http 链接实际是什么样子的，具体保持了那些内存信息？可以服用的基础是什么？（就像java线程池，我知道java 线程的实现是对系统函数的封装，java 线程本身就是个代理。并且没有在某一点暂停的直接方法，完成一个池只需要让线程不停止运行，即是从阻塞队列中不断获取任务，一个http 链接在系统中实际又是什么状态呢？？？） 能给我提供个思路吗？最好是从哪里，那本书可以找到相关的知识。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by fuyao-w** [comment]
> 问题已收到，http连接池这个东西你可以说详细点吗，比如用在什么场景？目前我能想到的是提供一个容器保存很多http链接而已
> […](#)
> ---原始邮件--- 发件人: "Wangfuyao"<notifications@github.com&gt; 发送时间: 2019年9月20日(星期五) 晚上9:44 收件人: "goctx/generic-pool"<generic-pool@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [goctx/generic-pool] 如何实现一个http 连接池？ (#3) 如何实现一个http 的连接池？我认为最终要的是我想保持的http 链接实际是什么样子的，具体保持了那些内存信息？可以服用的基础是什么？（就像java线程池，我知道java 线程的实现是对系统函数的封装，java 线程本身就是个代理。并且没有在某一点暂停的直接方法，完成一个池只需要让线程不停止运行，即是从阻塞队列中不断获取任务，一个http 链接在系统中实际又是什么状态呢？？？） 能给我提供个思路吗？最好是从哪里，那本书可以找到相关的知识。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

我觉得我需要了解的是一个http 连接在操作系统里面具体存储哪些实际的东西，场景可以是一个http 连接池？我不理解一次握手建立一条连接再断开后，保存在server 的一些资源可以不用重复创建，下次服用，还是什么其他的策略。

**Comment by xialeistudio** [comment]
http连接底层是一个TCP连接，操作系统会维护这个TCP连接，所有HTTP的消息传递基于这个TCP连接，操作系统不会为HTTP维护什么东西，因为HTTP是无状态协议

**Comment by fuyao-w** [comment]
那我应该取了解关于tcp 的东西包括在操作系统里怎么具体实现的，谢谢你的回答
